### ISSUE TITLE
Enable hibernate for POP_OS for swap partition

### ISSUE THREAD

**Issue by 0AlexZhong0** [abskmj/notes#3]
What should I do if I already have a swap and it is a partition instead of a `swapfile`?

**Comment by abskmj** [comment]
The steps are similar except for the `resume_offset` option which is not needed for the swap partition. I have updated the steps in the above commit for your reference.

**Comment by 0AlexZhong0** [comment]
> The steps are similar except for the `resume_offset` option which is not needed for the swap partition. I have updated the steps in the above commit for your reference.

Thanks, I will try it out shortly and let you know if it works. Cheers!
