### ISSUE TITLE
PopOS 20.10 on ASUS ROG Zephyrus G14 Laptop

### ISSUE THREAD

**Issue by S3f25hQyYc** [abskmj/notes#6]
Excellent guide!

### Machine
- ASUS ROG Zephryus G14 
- Model: GA401IV-BR9N6
- Nvidia 2060 Max-Q
- 16GB RAM
- 1TB NVME Drive
- PopOS 20.10 with NVIDIA, downloaded Jan 12, 2021 from System 76.
- See [website](https://www.bestbuy.com/site/asus-rog-zephyrus-g14-14-gaming-laptop-amd-ryzen-9-16gb-memory-nvidia-geforce-rtx-2060-max-q-1tb-ssd-moonlight-white/6403816.p?skuId=6403816).

### Installation Change Notes
- Used F2 key to access BIOS instead of ESC.
- After Modify Partitions, UEFI boot partition was smaller than 500MB, and there was a 16MB Microsoft reserved partition in 2nd position, followed by Windows partition. I deleted the reserved and Windows partitions, resized the UEFI boot to 502MB, and used the remaining unallocated space for EXT4.
- Installing the modules, I added sudo to the front of each command.s..

### Working
- Wifi
- Bluetooth Mouse, Speaker
- Suspend
- Nvidia graphics with games.
- Steam games, after selecting option to use Proton for two of them.
- Fan - quiet when cool, spins up when warm.
- Screen Brightness Fn+F7 Fn+F8
- Keyboard Backlight Fn+Up Fn+Down, also works after suspend.
- Super Key (Windows Key) after unlocking it Fn+Super
- Sound
- Dedicated Vol Up/Down keys above Fn key.
- Mute Volume using Fn+F1
- Play/Pause Fn+F3 works in YouTube.
- Suspend Fn+F11
- Airplane Mode Fn+F12
- Print Screen key, PrtSc
- Fractional Resolution at 125% after switching to Hybrid Graphics mode.
- Performace modes can be changed from in software, but not using hardware keys.

### Unknown
- Microphone mute button above Function keys. Pressing it doesn't change anything in settings like mute sound does.
- Fn+F6 ?

### Not Working
- Using Nvidia graphics - Fractional Resolution scaling in Settings --> Display. Doesn't work with Nvidia only graphics.
- Fingerprint Login
- Performance mode change above Function keys.
- Fn+F5 change performance mode doesn't seem to do anything.

**Comment by abskmj** [comment]
@S3f25hQyYc That's great to see that it is working for your model as well. I moved back to windows 10 as my primary driver mainly because of the Citrix receiver that I need for my work. The experience on Citrix receiver on Linux was not at par.
